# English Premier League (EPL) Pythagorean Predictor

## Step 1

In [1]:
# Load the packages

import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# Load the data. 
# EPL results for the 2017/18 season

EPL18 = pd.read_excel('Assignment Data/Week 1/EPL2017-18.xlsx')
print(EPL18.columns.tolist())
EPL18

['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR']

         Date        HomeTeam        AwayTeam  FTHG  FTAG FTR
0    20170811         Arsenal       Leicester     4     3   H
1    20170812        Brighton        Man City     0     2   A
2    20170812         Chelsea         Burnley     2     3   A
3    20170812  Crystal Palace    Huddersfield     0     3   A
4    20170812         Everton           Stoke     1     0   H
5    20170812     Southampton         Swansea     0     0   D
6    20170812         Watford       Liverpool     3     3   D
7    20170812       West Brom     Bournemouth     1     0   H
8    20170813      Man United        West Ham     4     0   H
9    20170813       Newcastle       Tottenham     0     2   A
10   20170819     Bournemouth         Watford     0     2   A
11   20170819         Burnley       West Brom     0     1   A
12   20170819       Leicester        Brighton     2     0   H
13   20170819       Liverpool  Crystal Palace     1     0   H
14   20170819     Southampton        West Ham     3     2   H
15   20170819           Stoke         Arsenal     1     0   H
16   20170819         Swansea      Man United     0     4   A
17   20170820    Huddersfield       Newcastle     1     0   H
18   20170820       Tottenham         Chelsea     1     2   A
19   20170821        Man City         Everton     1     1   D
20   20170826     Bournemouth        Man City     1     2   A
21   20170826  Crystal Palace         Swansea     0     2   A
22   20170826    Huddersfield     Southampton     0     0   D
23   20170826      Man United       Leicester     2     0   H
24   20170826       Newcastle        West Ham     3     0   H
25   20170826         Watford        Brighton     0     0   D
26   20170827         Chelsea         Everton     2     0   H
27   20170827       Liverpool         Arsenal     4     0   H
28   20170827       Tottenham         Burnley     1     1   D
29   20170827       West Brom           Stoke     1     1   D
..        ...             ...             ...   ...   ...  ..
350  20180428         Swansea         Chelsea     0     1   A
351  20180429      Man United         Arsenal     2     1   H
352  20180429        West Ham        Man City     1     4   A
353  20180430       Tottenham         Watford     2     0   H
354  20180504        Brighton      Man United     1     0   H
355  20180505     Bournemouth         Swansea     1     0   H
356  20180505         Everton     Southampton     1     1   D
357  20180505       Leicester        West Ham     0     2   A
358  20180505           Stoke  Crystal Palace     1     2   A
359  20180505         Watford       Newcastle     2     1   H
360  20180505       West Brom       Tottenham     1     0   H
361  20180506         Arsenal         Burnley     5     0   H
362  20180506         Chelsea       Liverpool     1     0   H
363  20180506        Man City    Huddersfield     0     0   D
364  20180508         Swansea     Southampton     0     1   A
365  20180509         Chelsea    Huddersfield     1     1   D
366  20180509       Leicester         Arsenal     3     1   H
367  20180509        Man City        Brighton     3     1   H
368  20180509       Tottenham       Newcastle     1     0   H
369  20180510        West Ham      Man United     0     0   D
370  20180513         Burnley     Bournemouth     1     2   A
371  20180513  Crystal Palace       West Brom     2     0   H
372  20180513    Huddersfield         Arsenal     0     1   A
373  20180513       Liverpool        Brighton     4     0   H
374  20180513      Man United         Watford     1     0   H
375  20180513       Newcastle         Chelsea     3     0   H
376  20180513     Southampton        Man City     0     1   A
377  20180513         Swansea           Stoke     1     2   A
378  20180513       Tottenham       Leicester     5     4   H
379  20180513        West Ham         Everton     3     1   H

[380 rows x 6 columns]

## Step 2

## Step 3

## Step 4 (home team)

## Step 5 (home team)

## Step 6 (home team)

## Optional steps, not required for Assessment 
### (Uncomment to run)

In [ ]:
# Plot the data

#sns.relplot(x="pyth17", y="wpc17", data =EPL17)

In [ ]:
# Run the regression

#pyth_lm = smf.ols(formula = 'wpc17 ~ pyth17', data=EPL17).fit()
#pyth_lm.summary()

## Step 7 (=Step 4 (away team))

## Step 7 (=Step 5 (away team))

## Step 7 (=Step 6 (away team))

## Optional steps, not required for Assessment
### (Uncomment to run)

In [ ]:
# Plot the data

#sns.relplot(x="pyth18", y="wpc18", data =EPL2018)

In [ ]:
# Run the regression

#pyth_lm = smf.ols(formula = 'wpc18 ~ pyth18', data=EPL2018).fit()
#pyth_lm.summary()

## Step 8

## Step 9

## Optional steps, not required for Assessment
### (Uncomment to run)

In [ ]:
#sns.relplot(x="pyth17", y="wpc18", data =Half2predictor)

In [ ]:
#sns.relplot(x="wpc17", y="wpc18", data =Half2predictor)

Now you have completed the assignment, are these results consistent with those we found for Major League Baseball?